name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g pkg
      - run: npm install
      - run: npx pkg app.js -o qqbot-chatgpt
      - name: Get Binary
        uses: actions/upload-artifact@v3
        with:
          name: bin
          path: qqbot-chatgpt